# Generated by Django 3.2.9 on 2021-12-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_game_date_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='developer',
            name='website',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
