# Generated by Django 3.2.9 on 2021-12-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211205_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
    ]
